services:
  avanza-api-prod:
    build:
      context: .
      target: avanza_api_prod
    container_name: avanza_api_prod
    ports:
      - "8001:8000"
    env_file: .env
    volumes:
      - "./:/app"
    networks:
      - avanza_net
    command: sh -c "gunicorn avanza_api.wsgi:application --bind 0.0.0.0:8000"

  avanza-celery-prod:
    build:
      context: .
      target: avanza_api_prod
    container_name: avanza_celery_prod
    env_file: .env
    volumes:
      - "./:/app"
    networks:
      - avanza_net
    command: sh -c "celery -A avanza_api worker --loglevel=info"

  avanza-celery-beat-prod:
    build:
      context: .
      target: avanza_api_prod
    container_name: avanza_celery_beat_prod
    env_file: .env
    volumes:
      - "./:/app"
    networks:
      - avanza_net
    command: sh -c "celery -A avanza_api beat --loglevel=info"

networks:
  avanza_net:
    external: true
