services:
  django:
    build:
      context: .
      target: api_dev
    container_name: admin_api
    #depends_on:
    #- mysql
    ports:
      - 8001:8000
    environment:
      MYSQL_USER: "admin_omar"
      MYSQL_USER_PASSWORD: "Chaday.@*"
      MYSQL_DATABASE: "admin_simbiosys_dev"
      MYSQL_HOST: "mysql.simbiosyserver.com"
      MYSQL_PORT: "3306"
      CELERY_BROKER_URL: redis://redis:6379/0
    volumes:
      - "./:/app"
    networks:
      - admin_net
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    #command: tail -f /dev/null

  mysql:
    # mysqldump --no-tablespaces -u admin_omar -p -h mysql.simbiosyserver.com admin_simbiosys > db.sql
    # mysql -u admin_omar -p -h mysql.simbiosyserver.com admin_simbiosys_dev < db.sql
    image: mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: "Chaday.@*"
      MYSQL_DATABASE: "admin_simbiosys"
      MYSQL_USER: "admin_omar"
      MYSQL_PASSWORD: "Chaday.@*"
    volumes:
      - admin_vol_mysql:/var/lib/mysql
      - "./db:/db"
    networks:
      - admin_net

  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - admin_net

  # celery-beat:
  #   build:
  #     context: .
  #     target: api_dev
  #   image: celery-beat
  #   container_name: celery-beat
  #   depends_on:
  #     - redis
  #   environment:
  #     MYSQL_USER: 'omar'
  #     MYSQL_USER_PASSWORD: 'secret'
  #     MYSQL_DATABASE: 'admin'
  #     HOST: 'mysql'
  #     PORT: '3306'
  #     CELERY_BROKER_URL: redis://redis:6379/0
  #   volumes:
  #     - './:/app'
  #   networks:
  #     - admin_net
  #   command: sh -c "celery -A PowerBi beat --loglevel=info"

  # celery:
  #   build:
  #     context: .
  #     target: api_dev
  #   image: celery
  #   container_name: celery
  #   depends_on:
  #     - redis
  #   environment:
  #     MYSQL_USER: 'omar'
  #     MYSQL_USER_PASSWORD: 'secret'
  #     MYSQL_DATABASE: 'admin'
  #     HOST: 'mysql'
  #     PORT: '3306'
  #     CELERY_BROKER_URL: redis://redis:6379/0
  #   volumes:
  #     - './:/app'
  #   networks:
  #     - admin_net
  #   command: sh -c "celery -A PowerBi worker --loglevel=info"

networks:
  admin_net:
volumes:
  admin_vol_mysql:
