# Generated by Django 6.0.4 on 2026-04-25 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0006_documentacion_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metros_terreno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Metros de terreno')),
                ('metros_construccion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Metros de construcción')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('habitaciones', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('banos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Baños')),
                ('medio_bano', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Medio baño')),
                ('niveles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cochera', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('antiguedad', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Antigüedad (años)')),
                ('mantenimiento', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mantenimiento (mensual $)')),
                ('calidad_construccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='catalogs.calidadconstruccion')),
                ('documento_propiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='catalogs.documentopropiedad')),
                ('equipamiento', models.ManyToManyField(blank=True, related_name='propiedades', to='catalogs.equipamiento')),
                ('estado_conservacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='catalogs.estadoconservacion')),
                ('gravamen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='catalogs.gravamen')),
                ('predial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='catalogs.predial')),
                ('servicios_corriente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='catalogs.servicioscorriente')),
                ('situacion_legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='catalogs.situacionlegal')),
                ('tipo_acabado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='catalogs.tipoacabado')),
                ('tipo_propiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='catalogs.tipopropiedad')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-created_at'],
            },
        ),
    ]
