# Generated by Django 6.0.4 on 2026-04-26 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
        ('sepomex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='asentamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to='sepomex.asentamiento', verbose_name='Colonia / Asentamiento'),
        ),
    ]
