# Generated by Django 6.0.4 on 2026-04-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_documentacion_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Antiguedad',
        ),
        migrations.DeleteModel(
            name='Banos',
        ),
        migrations.DeleteModel(
            name='Estacionamiento',
        ),
        migrations.DeleteModel(
            name='Habitaciones',
        ),
        migrations.DeleteModel(
            name='Niveles',
        ),
    ]
