# Generated by Django 6.0.4 on 2026-04-20 07:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaSepomex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_proceso', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('total_registros', models.IntegerField(default=0)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('mensaje', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Carga SEPOMEX',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='sepomex.estado')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['nombre'],
                'unique_together': {('clave', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='Asentamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.CharField(db_index=True, max_length=5)),
                ('nombre', models.CharField(max_length=60)),
                ('tipo', models.CharField(max_length=40)),
                ('zona', models.CharField(blank=True, max_length=20)),
                ('ciudad', models.CharField(blank=True, max_length=50)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asentamientos', to='sepomex.municipio')),
            ],
            options={
                'verbose_name': 'Asentamiento',
                'verbose_name_plural': 'Asentamientos',
                'indexes': [models.Index(fields=['codigo_postal'], name='sepomex_ase_codigo__9c08c4_idx'), models.Index(fields=['nombre'], name='sepomex_ase_nombre_f0611d_idx')],
            },
        ),
    ]
