# Generated by Django 5.1.4 on 2025-01-10 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='users',
            field=models.ManyToManyField(related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryprofile',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_prfile_by_location', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='kit',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes_by_material', to='inventory.material'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_by_material', to='inventory.material'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_by_status', to='inventory.status'),
        ),
        migrations.AddField(
            model_name='transactionregistry',
            name='src_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registries_as_source', to='inventory.transaction'),
        ),
        migrations.AddField(
            model_name='transactionregistry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registries_as_destination', to='inventory.transaction'),
        ),
        migrations.AddField(
            model_name='txndocument',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txn_documents_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='txndocument',
            name='from_user_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txn_documents_from_user_location', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='txndocument',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txn_documents_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='txndocument',
            name='to_user_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txn_documents_to_user_location', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='txndocument',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txn_documents_by_type', to='inventory.transactiontype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='txn_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_by_txn_document', to='inventory.txndocument'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='base_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_by_base_unit', to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_by_unit', to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='material',
            name='unit_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_by_unit_base', to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='kit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes_by_unit', to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='from_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_by_material', to='inventory.material'),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='to_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='inventory.unit'),
        ),
    ]
