# Generated by Django 5.1.4 on 2025-01-14 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='txndocument',
            old_name='date',
            new_name='txn_end_date',
        ),
        migrations.AddField(
            model_name='txndocument',
            name='txn_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
