# Generated by Django 5.1.4 on 2025-01-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_date_txndocument_txn_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txndocument',
            name='txn_start_date',
            field=models.DateTimeField(),
        ),
    ]
