# Generated by Django 6.0.4 on 2026-04-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(help_text='Número con código de país, ej: 524778938183', max_length=20)),
                ('facebook', models.URLField(blank=True, default='', max_length=500)),
                ('instagram', models.URLField(blank=True, default='', max_length=500)),
                ('tiktok', models.URLField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Configuración de Contacto',
                'verbose_name_plural': 'Configuración de Contacto',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
