# Generated by Django 6.0.4 on 2026-04-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasoExito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='casos_exito/')),
            ],
            options={
                'verbose_name': 'Caso de Éxito',
                'verbose_name_plural': 'Casos de Éxito',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
